import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { UserContextProvider } from "./context/UserContext";
import { SearchContextProvider } from "./context/SearchContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SearchContextProvider>
          <UserContextProvider>
            <Navbar></Navbar>
            {children}
          </UserContextProvider>
        </SearchContextProvider>
      </body>
    </html>
  );
}
