import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { UserContextProvider } from "./context/UserContext";
import { SearchContextProvider } from "./context/SearchContext";
import { ProfileContextProvider } from "./context/ProfileContext";
import initTranslations from "./i18n";
import TranslationsProvider from "./components/TranslationsProvider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lock.in",
  description: "Generated by create next app",
};

const i18nNamespaces = [
  "mainpage",
  "common",
  "navbar",
  "findPlayer",
  "login",
  "register",
];

export default async function RootLayout({ children, params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang="en">
      <body className={inter.className}>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          <ProfileContextProvider>
            <SearchContextProvider>
              <UserContextProvider>
                <Navbar></Navbar>
                {children}
                <Toaster richColors position="bottom-right"></Toaster>
              </UserContextProvider>
            </SearchContextProvider>
          </ProfileContextProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
