import { Inter } from "next/font/google";
import "@fontsource/bangers";
import "@fontsource/chewy";
import "@fontsource/rum-raisin";
import "@fontsource/dekko";
import "@fontsource/poetsen-one";
import "./globals.css";
import ClientLayout from "./clientLayout";
import { UserContextProvider } from "./context/UserContext";
import { SearchContextProvider } from "./context/SearchContext";
import { ProfileContextProvider } from "./context/ProfileContext";
import { LanguageContextProvider } from "./context/LanguageContext";
import initTranslations from "./i18n";
import TranslationsProvider from "./components/TranslationsProvider";

const inter = Inter({ subsets: ["latin", "latin-ext"] });

export const metadata = {
  title: "Lock.in",
  description: "Generated by create next app",
};

const i18nNamespaces = [
  "mainpage",
  "common",
  "navbar",
  "findPlayer",
  "login",
  "register",
  "footer",
  "builds",
  "duo",
  "courses",
  "settings",
  "comments",
  "riot",
];

export default async function RootLayout({ children, params: { locale } }) {
  const { t, resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TranslationsProvider
          resources={resources}
          locale={locale}
          namespaces={i18nNamespaces}
        >
          <LanguageContextProvider>
            <ProfileContextProvider>
              <SearchContextProvider>
                <UserContextProvider>
                  <ClientLayout>{children}</ClientLayout>
                </UserContextProvider>
              </SearchContextProvider>
            </ProfileContextProvider>
          </LanguageContextProvider>
        </TranslationsProvider>
      </body>
    </html>
  );
}
